name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v4.9.1
        with:
          python-version: 3.12
      - uses: actions/cache@v4.2.3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install git+https://taddyb:${{ secrets.GHCR_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install pillow cairosvg mkdocs-git-committers-plugin mkdocs-material-extensions mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin
      - run: mkdocs build
      - run: mkdocs gh-deploy --force
